apiVersion: "v1"
name: floki
version: 0.0.5
appVersion: v0.0.1
kubeVersion: "^1.10.0-0"
description: "Uses Floki to tail kafka and send them to Loki"
home: https://github.com/nosinovacao/floki
icon: https://github.com/nosinovacao/floki/tree/master/images/floki.png
sources:
- https://github.com/nosinovacao/floki
maintainers:
- name: AAAAAAAAA
  email: AAAAAAAAA
engine: gotpl
